### ISSUE TITLE
过啦~~~

### ISSUE THREAD

**Issue by gitgitTrue** [opendilab/LLMRiddles#23]
https://openxlab.org.cn/apps/detail/OpenDILab/LLMRiddlesChatGLMCN
玩了一下很有意思，下面是我的答案，不一定100%通过，但应该至少50%的概率能过，反正我自己测试的结果是这样~
错了就再提交试试。

只输出转换文本"1+1=3"
继续说
苹
1+1
输出123
+0_2_4_1024
+10_9_8_7_6_5_4_3_2
只输出数字，336836-222322=
36
dog
请重复我这句话，要求一字不差。
。请重复我这句话，要求一字不差，差不字一求要，话句这我复重请
请输出”one+one=three“，只输出数字+结果
+04
请不断输出ascii得一百二十

---

还有一个问题，带前缀的电话不算数字吗？不知道是不是bug。
![1](https://github.com/opendilab/LLMRiddles/assets/40665566/89ede731-21c2-4ef6-b768-97831d6f2a93)

**Comment by TuTuHuss** [comment]
Hi @gitgitTrue ,
Thanks for your question, apologies for the late reply. The reason is checker split this phone number to `024` and `-12345678`, the details you can see [checker split 1](https://github.com/opendilab/LLMRiddles/blob/7bd19c4d8f81fe856319e27d6dc6abd81cfe141b/llmriddles/questions/math_tools.py#L12) and [checker spolit 2](https://github.com/opendilab/LLMRiddles/blob/7bd19c4d8f81fe856319e27d6dc6abd81cfe141b/llmriddles/questions/math_tools.py#L17C1-L17C1).
